### PR TITLE
Update neuroconv logo

### PR DESCRIPTION
**Pull request by oruebel**

### CODE REVIEW

**Comment by rly** [comment]
The top of the brain outline is a little squished. Could you stretch it up a bit?

**Comment by oruebel** [comment]
> The top of the brain outline is a little squished. Could you stretch it up a bit?

That's the version of the logo that @CodyCBakerPhD had sent. Happy to update the logo, but then we should updated in NeuroConv first.

**Comment by CodyCBakerPhD** [comment]
> The top of the brain outline is a little squished. Could you stretch it up a bit?

Not sure what you mean - that's the right logo

**Comment by rly** [comment]
Sorry, I was confused. I thought this was proposing a new logo for Neuroconv (yes, this would be an odd place to propose that).

Aside: I don't see the logo online on the github or readthedocs. 

@CodyCBakerPhD If you are open to modifying the logo, I suggest stretching the top of the brain outline upwards a bit because it looks squished.

**Review by rly — APPROVED** [review]

**Pull request merged**
