### PR TITLE
Add BMTK tool

### LINKED ISSUE #141: Add Allen Institute Brain Modeling Toolkit (BMTK) / SONATA
https://github.com/AllenInstitute/bmtk

### PR DESCRIPTION
**Pull request by oruebel**
Fix #141

### CODE REVIEW

**Comment by oruebel** [comment]
@kaeldai here a draft for adding BMTK to the tools index. 

Does BMTK / Sonata also support output in NWB or only input as stimulus? I know that there were efforts when Sonata was released to have converters to NWB but I thought BTMK may also be able to output NWB directly. 

* https://github.com/AllenInstitute/sonata/blob/master/tutorials/nwb_sonata/nwb_tutorial.ipynb
* https://github.com/catalystneuro/ndx-simulation-output

**Comment by oruebel** [comment]
CC @bendichter

**Comment by oruebel** [comment]
You can view the page here:

- Entry in the index: https://nwb-overview--146.org.readthedocs.build/en/146/tools/acquisition_tools_home.html#brain-data-modeling-and-simulation
- BMTK full page: https://nwb-overview--146.org.readthedocs.build/en/146/tools/bmtk/bmtk.html#analysistools-bmtk

We can add more details on the full page, e.g., to describe in more detail how BMTK / Sonada support NWB

**Review by kaeldai — APPROVED** [review]

**Comment by kaeldai** [comment]
Hi @oruebel - Sorry for not getting back sooner. 

To answer your question, bmtk does have some limited support for writing output to NWB. At the moment you can specify spikes be written to nwb format in which case it will save simple spike train information (id and spike-times) to the Units table. Although there was just a noticed bug so that feature still needs a bit of work to be fully compliant. Also I realized it isn't documented which I'll have to do!

Otherwise, I read the description on the index and I think it encompasses the core NWB utility in bmtk really well. I think it should be fine to merge in the language that you already have. Thanks! Kael

**Review by bendichter — APPROVED** [review]

**Pull request merged**
