### PR TITLE
Add nwb project analytics 

### LINKED ISSUE #127: Make .readthedocs.yaml

### LINKED ISSUE #129: Broken link in file read page
The following link on the file read page is currently broken:

`(file_read/file_read: line   11) broken    https://pynwb.readthedocs.io/en/stable/tutorials/general/read_basics.html - 404 Client Error: Not Found for url: https://pynwb.readthedocs.io/en/stable/tutorials/general/read_basics.html`

### PR DESCRIPTION
**Pull request by oruebel**
This PR adds a new section *NWB Software Analytics* to show the pages generated using the [nwb-project-analytics](https://github.com/NeurodataWithoutBorders/nwb-project-analytics) repo.

Screen Shot 2023-08-19 at 4 14 35 PM

**This PR makes the following main changes:**

- [x] Added readthedoc.yaml required for RTD to control docs build Fix #127 
- [x] Added nwb-project-analytics as a requirement and update requirements
- [x] Created `conf_nwb_analytics.py` script to download and build the nwb_project_analytics
- [x] Updated `conf.py` to call `conf_nwb_analytics.py` to build the project analytics pages
- [x] Updated `index.rst` to include the project analytics pages
- [x] Updated the sphinx `Makefile` to clean nwb_project_analytics on `make clean`
- [x] Update `.gitignore` to ignore nwb_project_analytics
- [x] Fix broken link in file read page Fix #129
- [ ] Automatically trigger daily rebuild of docs on ReadTheDocs

### CODE REVIEW

**Comment by oruebel** [comment]
@rly do you have a suggestion for a good way to automatically trigger daily rebuilds of the `nwb-overview` on ReadTheDocs? The `nwb_project_analytics` are updated nightly via a GitHub action, however, that does not trigger a rebuild of the `nwb-overview` page since nothing changes in that repo. It would be nice to also have the `nwb-overview` page re-render nightly to make sure the software statistics are being updated automatically, rather than being updated only when we update `nwb-overview` itself.

**Comment by oruebel** [comment]
@bendichter @rly this PR is ready for review. The only part missing is to trigger nightly or weekly rebuilds of the nwb-overview RTD page, but I think that might be a setting in RTD, rather than something we need to change here.

**Comment by rly** [comment]
> @rly do you have a suggestion for a good way to automatically trigger daily rebuilds of the `nwb-overview` on ReadTheDocs? 

I cannot see a way to do it in ReadTheDocs. However, we could add a silly workflow in this repo that creates a new commit to the main branch That would trigger a new ReadTheDocs build. But it would definitely clutter the git history...

**Review by rly — APPROVED** [review]

**Comment by oruebel** [comment]
> However, we could add a silly workflow in this repo that creates a new commit to the main branch 

I think we may be able to trigger builds via the RTD API directly. https://docs.readthedocs.io/en/stable/api/v3.html#build-triggering

We could do this in a workflow here or we could add it to the workflow on nwb_project_analytics that updates the stats.

**Pull request merged**
