### PR TITLE
Add overview of the NWB documentation to next steps section

### LINKED ISSUE #29: Create page with overview of NWB documentation resources
Describe the orgnization of and where folks can find different documentation for their needs.

### PR DESCRIPTION
**Pull request by oruebel**
Fix #29 

This PR adds a section on the front page to provide an overview of the main available documentation resources with the goal to: a) give users an idea what resources are available to them and b) help folks navigate the documentation at large.

### CODE REVIEW

**Comment by rly** [comment]
I appreciate this guide but I am concerned this is too much meta-level text/information for new users and would be intimidating. What do you think about moving this or some form of it to the end of the user guide?

**Comment by bendichter** [comment]
I don't know about the placement of things on the pyramid. I think about the relationships between these tools pretty differently. For instance, it seems unintuitive to me to have the NWB schema below HDMF, since it uses essentially the HDMF schema language. Likewise community tools should be above the APIs, since they almost always use either PyNWB or MatNWB.

**Comment by oruebel** [comment]
> What do you think about moving this or some form of it to the end of the user guide?

Sounds good to me.

**Comment by oruebel** [comment]
> I don't know about the placement of things on the pyramid. 

@bendichter I was less thinking in terms of a software stack, but rather in terms of level-of-detail and the order in which a user will typically encounter the documents. I think moving the "Data Modeling" part to the bottom of the Pyramid makes sense. I'll see what I can do about the tools, but I don't want to have the tools appear on top of th APIs because that would mess up the separation between the left/right half of the figure.

**Comment by oruebel** [comment]
@bendichter @rly please have a look to see if this works better now. I've move the text to make it a subsection as part of the "Next Steps" section at the end of the intro. I've also updated the figure to more closely match the ordering that Ben suggested and updated the text accordingly.

**Review by bendichter — APPROVED** [review]

**Pull request merged**
