### PR TITLE
Add page for extension best practices

### PR DESCRIPTION
**Pull request by oruebel**
This PR adds a page for describing best practices for creating NWB extensions

### CODE REVIEW

**Comment by oruebel** [comment]
@rly @bendichter this is just a first rough draft for some best practices for defining extensions. Please feel free to add more best practices or to add comments with other best practices here so that I can add them to the list.

**Comment by bendichter** [comment]
@oruebel I really like the idea of adding this and I also like all of the content. I just wonder where is the best place to put this? I think perhaps it would be better to put this in the Best Practices document and then link to it here. That way we could build tests in the NWB Inspector that explicitly link to this.

@CodyCBakerPhD, what do you think? Would you want to build automated tests for these best practices? If so, what would be the best way to do it? I suppose it would be possible to build an inspector that inspects an extension YAML directly, though it would be outside the abilities of our current inspector function. Would that impact the best place to put this document?

**Comment by CodyCBakerPhD** [comment]
Hmm... so the goal would be to...

(a) be able to run `nwbinspector my_nwb_extension_schema.yaml` 

and have it run

(b) checks that are specific to a schema for an NWB extension

That should not be too hard. What we're talking about is creating a separate registry of checks.

The current registry of checks is a list of functions specific to usage existing NWB files on disk or in-memory instances of `NWBFile`s.

For the on-disk usage, we'd just add a logic splitter based on if you're pointing to a `.nwb` file or a `.yaml` (schema) file, and determine which registry to use based on that.

Will think more on what the logic in the YAML-specific check functions would look like.

**Comment by oruebel** [comment]
> I think perhaps it would be better to put this in the Best Practices document and then link to it here.

I think that's reasonable. However, I would suggest creating a separate section as not to mix best practices for data and best practices for creating extensions.

> That should not be too hard. What we're talking about is creating a separate registry of checks.

That makes sense to me and I think also makes sense from a user perspective. I.e., similar to how we deal with actual data, PyNWB ensures that things are structurally valid (here, that an extension YAML is a valid schema) and the Inspector looks deeper at the actual content to ensure it follows best practices. If it fits nicely into the design of the NWBInspector then I think that's a good way to go.

**Comment by oruebel** [comment]
Closing this PR since write-up of extension best practices has moved to the NWB Inspector.

**Pull request closed without merging**
