### PR TITLE
add github stars

### PR DESCRIPTION
**Pull request by bendichter**
I think this is a nice unbaissed way for us to indicate the popularity of each of these tools. What does everyone think?

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Is there a way to standardize the position of the badge display on the docs?

image

**Comment by oruebel** [comment]
> Is there a way to standardize the position of the badge display on the docs?

It's a matter of the size of the logo. I.e., eventually the text wraps around the logo.  If you want everything to show on the right of the logo, you'd need to add empty space to the logo.

**Comment by bendichter** [comment]
or we could create a more sophisticated layout, like creating tables or divs. I think this page might eventially benefit from some templating, e.g. hugo.

**Comment by bendichter** [comment]
Unrelated to these changes, it looks like the HDF Group is reorganizing their website, which is breaking a bunch of links:

```
tools/hdftools/hdftools: line   89) broken    https://portal.hdfgroup.org/display/HDF5/h5copy - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5copy
(tools/hdftools/hdftools: line   91) broken    https://portal.hdfgroup.org/display/HDF5/h5clear - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5clear
(tools/analysis_tools_home: line    3) broken    https://portal.hdfgroup.org/display/HDF5/HDF5+Command-line+Tools - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/HDF5+Command-line+Tools
(tools/hdftools/hdftools: line   81) broken    https://portal.hdfgroup.org/display/HDF5/h5check - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5check
(tools/hdftools/hdftools: line   80) broken    https://portal.hdfgroup.org/display/HDF5/h5diff - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5diff
(tools/hdftools/hdftools: line   79) broken    https://portal.hdfgroup.org/display/HDF5/h5dump - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5dump
(tools/hdftools/hdftools: line   72) broken    https://portal.hdfgroup.org/display/HDF5/h5ls - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5ls
(tools/hdftools/hdftools: line   90) broken    https://portal.hdfgroup.org/display/HDF5/h5repart - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5repart
(tools/hdftools/hdftools: line   88) broken    https://portal.hdfgroup.org/display/HDF5/h5repack - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5repack
(tools/hdftools/hdftools: line   82) broken    https://portal.hdfgroup.org/display/HDF5/h5stat - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5stat
(tools/hdftools/hdftools: line   83) broken    https://portal.hdfgroup.org/display/HDF5/h5watch - 404 Client Error: Not Found for url: https://portal.hdfgroup.org/display/HDF5/h5watch
```

**Comment by bendichter** [comment]
HDF5 links are down temporarily:

image

**Review by oruebel — APPROVED** [review]

**Pull request merged**
